version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - postgres_kc_data:/var/lib/postgresql/data
    ports:
      - 5431:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: jboss/keycloak
    volumes:
      - ./config/keycloak-login-page/:/opt/jboss/keycloak/themes/sodas/
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin.123
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8443:8443
    depends_on:
      - postgres
volumes:
  postgres_kc_data:
      driver: local