version: '3'
services:
  platform:
    build:
      context: .
      dockerfile: nodejs_dockerfile
    depends_on:
      - postgres
    working_dir: /usr/src/app
    volumes:
      - ../../:/usr/src/app
    ports:
      - 13000:3000
    command: npm run docker:test
  postgres:
    image: postgres:10-alpine
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
      - ../../migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: sodas_dev
      POSTGRES_DB: sodas_dev
      POSTGRES_USER: sodas_dev_user
      POSTGRES_PASSWORD: sodas_dev_secret
    ports:
      - 15432:5432
volumes:
  postgres-dev-data:
